# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f32cba6c7f9cfbc37503e64a6dfd8e23ba60fea71ba26b33a5963ccd6f1fb55c34042c61ea2f136ace9a86b4c4eca6b91c07e8de41a4beb8c2593baba8d5e55

test:
  secret_key_base: f86d4a580f62685bfedfa7707fce6b6f1feb606034c8e8e1d3f61c20134c916c6f9e0fc89f506c7156e98ad5b9efd3abafb060699a134259203b21c3e161bbc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
